version: '3.8'

services:
  chess-analyzer:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/player/hikaru/profile"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
